name: jobfe
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  enefty_icons: ^1.0.7
  fluentui_system_icons: ^1.1.239
  carousel_slider: ^5.0.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  flutter_toggle_tab: ^1.5.1
  intl: ^0.19.0
  one_context: ^4.0.0
  file_picker: ^8.0.5
  http: ^1.2.1
  universal_html: ^2.2.4
  dotted_border: ^2.1.0
  syncfusion_flutter_pdfviewer: ^29.2.4
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  url_launcher: ^6.3.0
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/loginbg.svg
    - assets/images/loginbg.png
    - assets/images/promo.jpg
    - assets/images/icon.png
    - assets/images/mycvicon.png
    - assets/images/mycompany.png
    - assets/images/salaryconvert.png
    - assets/images/fail.png
    - assets/images/splashscreen.svg
    - assets/images/darksplashscreen.svg
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/zalo.png
    - assets/images/facebook_icon.png
